# Generated by Django 3.2 on 2023-02-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bills",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="BillName")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_paid", models.BooleanField()),
                ("slug", models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="HousingAssociation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=254, unique=True, verbose_name="HousingName")),
            ],
        ),
        migrations.RemoveField(
            model_name="management",
            name="member",
        ),
        migrations.RemoveField(
            model_name="member",
            name="name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="role",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="apartment",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="category",
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="description",
            new_name="text",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="apartment",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="news",
            name="date",
        ),
        migrations.AddField(
            model_name="apartment",
            name="balance",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="address",
            field=models.CharField(max_length=100, unique=True, verbose_name="ApartmentAddress"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="area",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="slug",
            field=models.SlugField(max_length=40),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Management",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
        migrations.AddField(
            model_name="bills",
            name="apartment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="manager.apartment"),
        ),
        migrations.AddField(
            model_name="apartment",
            name="housing",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="manager.housingassociation"
            ),
            preserve_default=False,
        ),
    ]
