# Generated by Django 3.2 on 2023-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_auto_20230215_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="bills",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="housingassociation",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
