# Generated by Django 3.2 on 2023-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_auto_20230216_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingassociation",
            name="slug",
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
