# Generated by Django 3.2 on 2023-02-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_apartment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apartment",
            name="balance",
        ),
        migrations.AddField(
            model_name="apartment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
