# Generated by Django 3.2 on 2023-02-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_rename_amount_apartment_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="end_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
