# Generated by Django 3.2 on 2023-02-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_alter_bill_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='housingassociation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
