# Generated by Django 3.2 on 2023-02-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20230222_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='name',
        ),
    ]
