# Generated by Django 3.2 on 2023-02-23 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_bill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
