# Generated by Django 3.2 on 2023-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_bill_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
    ]
