# Generated by Django 3.2 on 2023-02-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_bill_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='occupant',
            field=models.IntegerField(default=0),
        ),
    ]
