# Generated by Django 3.2 on 2023-02-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_issue_issuestatus_issuetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuestatus',
            options={'verbose_name_plural': 'Issue statuses'},
        ),
        migrations.AlterField(
            model_name='issuestatus',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='issuetype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
