# Generated by Django 3.2 on 2023-02-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20230223_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_status', to='manager.issuetype'),
        ),
    ]
