# Generated by Django 3.2 on 2023-02-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_bill_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='billtype',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.billsubtype'),
        ),
    ]
