# Generated by Django 3.2 on 2023-02-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_bill_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='is_paid',
            new_name='is_balanced',
        ),
    ]
