# Generated by Django 3.2 on 2023-02-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingbill',
            name='housing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.housingassociation'),
        ),
    ]
