# Generated by Django 3.2 on 2023-02-25 14:36

import apps.manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_auto_20230225_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='account',
            field=models.DecimalField(decimal_places=0, default=apps.manager.models._account, max_digits=26),
        ),
    ]
