# Generated by Django 3.2 on 2023-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0041_alter_apartment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
